export async function executeBotCode(botCode, context) {
    const {
      sendTextMessage,
      sendImageMessage,
      sendVideoMessage,
      sendDocumentMessage,
      sendAudioMessage,
      sendTemplateMessage,
      sendTemplateToSingleContact,
      sendLocationMessage,
      io,
      senderId,
      messageData,
      conversationId,
      pool,
      axios,
      getContactInfo,
      updateContactName,
      createContact,
      updateContactCompany,
      updateConversationState,
      assignResponsibleUser,
      processMessage,
      getReverseGeocoding,
      getGeocoding,
      integrationDetails,
      externalData,
      clientTimezone,
      moment
    } = context;
  
    try {
      const botFunction = new Function(
        'sendTextMessage',
        'sendImageMessage',
        'sendVideoMessage',
        'sendDocumentMessage',
        'sendAudioMessage',
        'sendTemplateMessage',
        'sendTemplateToSingleContact',
        'sendLocationMessage',
        'io',
        'senderId',
        'messageData',
        'conversationId',
        'pool',
        'axios',
        'getContactInfo',
        'updateContactName',
        'createContact',
        'updateContactCompany',
        'updateConversationState',
        'assignResponsibleUser',
        'processMessage',
        'getReverseGeocoding',
        'getGeocoding',
        'integrationDetails',
        'externalData',
        'clientTimezone',
        'moment',
        botCode
      );
  
      await botFunction(
        sendTextMessage,
        sendImageMessage,
        sendVideoMessage,
        sendDocumentMessage,
        sendAudioMessage,
        sendTemplateMessage,
        sendTemplateToSingleContact,
        sendLocationMessage,
        io,
        senderId,
        messageData,
        conversationId,
        pool,
        axios,
        getContactInfo,
        updateContactName,
        createContact,
        updateContactCompany,
        updateConversationState,
        assignResponsibleUser,
        processMessage,
        getReverseGeocoding,
        getGeocoding,
        integrationDetails,
        externalData,
        clientTimezone,
        moment
      );
    } catch (error) {
      console.error('Error ejecutando el código del bot:', error);
    }
  }